config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }  
  
  resources :posts do
    resources :comments
  end
  
  root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy
  
  paginates_per 3
  
  validates :image, presence: true
  validates :user_id, presence: true
  validates :caption, presence: true, length: { minimum: 4, maximum: 150 }
  
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Check your comment again, it could not be added."
      render root_path
    end
  end
  
  def destroy
    @comment = @post.comments.find(params[:id])
   
    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end
  
  # _____________________________________________-
  private
  
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def get_post
    @post = Post.find(params[:post_id])
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
        flash[:success] = "Your post has been created successfully!"
        redirect_to posts_path
    else
        flash.now[:alert] = "Your post could not be created. Try again."
        render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Your post has been updated."
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "Update failed. Please try again."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  # ___________________________________________________________________
  
  private
  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def get_post
    @post = Post.find(params[:id])
  end
  
  def owned_post  
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_for(flash_type)  
        { success: 'alert-success', error: 'alert-danger',
          alert: 'alert-warning', notice: 'alert-info'
        }[flash_type.to_sym] || flash_type.to_s
    end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
#comment
  %span.comment-author.text-info.text-bold= comment.user.user_name
  %span.comment-cntnt= comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, remote: true do
      .glyphicon.glyphicon-remove.text-muted.pull-right
  %br

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        =link_to root_path do
          %span.glyphicon.glyphicon-camera
          Instagrails
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "About", root_path
        - if user_signed_in?
          %li= link_to "New Post", new_post_path
          %li
            = link_to destroy_user_session_path, method: :delete do
              = "Logout (<span class='text-info'>".html_safe + current_user.user_name + "</span>)".html_safe
        - else
          %li= link_to "Login", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Instagrails
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    /.container
    .container
      .row 
        - flash.each do |name, msg|
          = content_tag :div, msg, class: [:badge, alert_for(name)]
      = yield
      .row
        %h5.text-center
          %span.text-danger.text-bold.label.label-info= "Instagrails " + Time.now.year.to_s

app/views/posts/_form.html.haml
.row
  .col-md-offset-1.col-md-10
    = simple_form_for @post, html: { class: 'form form-horizontal', multipart: true } do |f|
      .form-group.text-center
        %h4 Upload an image:
        %br
        = f.input :image, label: false
      .form-group
        = f.input :caption, label: false, placeholder: 'Add your caption', input_html: {class:"form-control"}
      .form-group.pull-right
        = f.button :submit, class: "btn btn-sm btn-success"
        = link_to "Cancel", root_path, class: "btn btn-sm btn-danger"

app/views/posts/_post.html.haml
.panel.panel-default
  .panel-heading
    %h5.pull-right.text-muted.small= time_ago_in_words(post.created_at)
    =image_tag "avatar.png", { class: "img img-responsive img-circle pull-left" }
    %h5.text-info= "<strong>".html_safe + post.user.user_name + "</strong>".html_safe
  .panel-body
    =link_to (image_tag post.image.url(:medium), {:class => "img img-responsive"}), post_path(post)
  .panel-footer
    %span.post-caption
      .text-info.caption-author.pull-left= post.user.user_name
      =post.caption
    %br
      
    .comments{id: "comments_#{post.id}"}
      - if post.comments
        = render post.comments, post: post

    %hr
    .row#add-comment-div
      .col-xs-1
        %span.glyphicon.glyphicon-heart-empty
      .col-xs-11
        = form_for([post, post.comments.build], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...',
          class: "form-control add-comment-input", id: "comment_content_#{post.id}"

app/views/posts/edit.html.haml
.row
  .col-md-4.col-md-offset-4
    .well.well-sm
      = image_tag @post.image.url(:medium), {:class => "img img-responsive"}
        
.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      = render "form"
    %p.text-right
      %span= link_to "Delete Post", post_path(@post), :class => "btn btn-xs btn-warning", method: :delete

app/views/posts/index.html.haml
.visible-md.visible-lg
  /%h3.text-danger What's new?
  /%h4 Take a look at those pictures
  /%hr
  
- @posts.each do |post|
  .row  
    .col-md-6.col-md-offset-3
      = render "post", post: post
    
.row
  .col-md-12.text-center
    = paginate @posts 

app/views/posts/new.html.haml
.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      = render "form"

app/views/posts/show.html.haml
.row  
  .col-md-6.col-md-offset-3
    = render "post", post: @post
    %p.text-right
      - if @post.user.id == current_user.id
        %span= link_to "Edit this post", edit_post_path(@post), {:class => "btn btn-xs btn-warning"}
      %span= link_to "Go back to all posts", posts_path, {:class => "btn btn-xs btn-default"}  